/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'breckwagner' at '11/25/15 11:45 PM' with Gradle 2.6
 *
 * @author breckwagner, @date 11/25/15 11:45 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
